# 公式渲染
mathjax:
  enable: true
# 文章信息
postInfo:
  update: true # 更新日期
  wordCount: true # 文章字数统计
  totalCount: true # 站点总文章字数
  min2read: true # 文章阅读时长
  readCount: true # 文章阅读次数
mermaid:
  enable: true
hexo_markmap:
#  pjax: false
  katex: true
#  prism: false
#  CDN:
#    d3_js: https://fastly.jsdelivr.net/npm/d3@6
#    markmap_view_js: https://fastly.jsdelivr.net/npm/markmap-view@0.2.7
#    katex_css: https://fastly.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css
#    prism_css: https://fastly.jsdelivr.net/npm/prismjs@1.25.0/themes/prism.css