name: Sync To Parent Repository
on: [ push, delete, create ]
jobs:
  hexo-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Private Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - name: git config
        env:
          USER_NAME: 'wangjueya_ci'
          USER_EMAIL: '573711282@qq.com'
        run: |
          git config --global user.name "$USER_NAME"
          git config --global user.email "$USER_EMAIL"
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: c-hive/gha-yarn-cache@v1
      - name: Yarn install
        run: yarn install
      - name: Hexo deploy
        run: yarn run deploy