name: Sync To Parent Repository
on: [ push, delete, create ]
jobs:
  hexo-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Private Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
      - name: git config
        env:
          USER_NAME: 'wangjueya_ci'
          USER_EMAIL: '573711282@qq.com'
        run: |
          git config --global user.name "$USER_NAME"
          git config --global user.email "$USER_EMAIL"
          git config --global core.quotepath false
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Git commit
        run: |
          git submodule update --init --recursive
          git submodule update --remote
          echo "构建时提交一份最新的代码"
          git add *
          git commit -m ":construction_worker: [skip ci] Auto Update"
          git push origin master
      - uses: c-hive/gha-yarn-cache@v1
      - name: Yarn install
        run: |
          echo "修复自动构建时所有文章更新时间为当前时间问题 | 取git提交时间"
          cd source/_posts # 子模块更新失败问题
          git ls-tree -r --name-only HEAD | while read filename; do
          echo $filename;
          unixtime=$(git log -1 --format="%at" -- "${filename}");
          touchtime=$(date -d @$unixtime +'%Y%m%d%H%M.%S');
          echo "${filename} --- ${touchtime}"
          touch -t ${touchtime} "${filename}";
          done
          cd ../../
          yarn install
      - name: Hexo deploy
        run: |
          yarn run clean
          yarn run deploy
