name: Sync To Parent Repository
on: [ push, delete, create ]
jobs:
  hexo-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: c-hive/gha-yarn-cache@v1
      - name: Yarn install
        run: yarn install
      - name: Hexo deploy
        run: yarn run deploy